### ISSUE TITLE
wrong 'line' count in tokenize for fields 'cpp' and 'cxx_comment'

### ISSUE THREAD

**Issue by Lotharla** [benkasminbullock/C-Tokenize#14]
Concerning the subroutine 'tokenize' i found that the 'line' member in the token hash counts just one too much in case of the fields 'cpp' and 'cxx_comment'.
It seems that the algorithm is fed with too many new-lines by the regex. The reason i see for that lies in the patterns 'cpp_re' and 'cxx_comment_re'.
If you remove the "trailing" new-lines (\n) in these pattern you can get the line count right ... plus your test module C-Tokenize.t agrees.

**Comment by benkasminbullock** [comment]
Thank you for reporting this. On inspecting the code it seemed not to have any tests of behaviour at all for the line numbers. Could you add a patch for your expected behaviour and if possible a test? If you are not familiar with adding tests to CPAN modules, please let me know and I'll try to help with this.

Thanks again.

**Comment by Lotharla** [comment]
I 'll write a test case for the CPAN module and send it to you .. is it that what you are saying ... 
In case you want me to add the test to the CPAN module myself, then please tell me in 140 chars what i need to do, so i don't have to look it up somewhere or send me the link. 
-Lothar 


     On Sunday, November 15, 2015 4:48 AM, Ben Bullock <notifications@github.com> wrote:
   

 Thank you for reporting this. On inspecting the code it seemed not to have any tests of behaviour at all for the line numbers. Could you add a patch for your expected behaviour and if possible a test? If you are not familiar with adding tests to CPAN modules, please let me know and I'll try to help with this.Thanks again.—

**Comment by Lotharla** [comment]
Hi Ben, i think i can make my point without writing a test case, although test routines are very useful, i know.First, I like your C-tokenizing solution because it is a hands-on approach using regular expressions. Ideally it should tokenize any valid C source file. 
So here is an example that doesn't work with 'C-Tokenize-0.09'. Take any valid C source, let 's call it main.c. Now write another C source _main.c which just contains a single preprocessor directive: #include "main.c". Make sure _main.c has no new-line at the end. This is also a valid C source which compiles the same way main.c does. 
C-Tokenizer will tokenize _main.c to an empty array.The reason is that the regular expression '$cpp_re' requires a new-line character at the end of a cpp directive that _main.c doesn't need.The same would be true for a '//'-style comment at the end of C source and no new-line ... it is not recognized by the tokenizer.Another consequence concerns the 'line' members in the hashes of the resulting array of hashes. These values are not correct after the tokenizer hit a cpp directive or a cxx-style comment because the regex swallows a new-line which isn't available any more for the line number incrementing.Hope this helps, 
Lothar
 


    On Sunday, November 15, 2015 4:48 AM, Ben Bullock <notifications@github.com> wrote:
 

 Thank you for reporting this. On inspecting the code it seemed not to have any tests of behaviour at all for the line numbers. Could you add a patch for your expected behaviour and if possible a test? If you are not familiar with adding tests to CPAN modules, please let me know and I'll try to help with this.Thanks again.—

**Comment by benkasminbullock** [comment]
Thanks for making your point.
